// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notification_AWS.Helpers;

#nullable disable

namespace Notification_AWS.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Notification_AWS.Models.Files", b =>
                {
                    b.Property<string>("Filename")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Filesize")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Last_modified")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Filename");

                    b.ToTable("dbo.pessoas");
                });
#pragma warning restore 612, 618
        }
    }
}
